PRAGMA foreign_keys=OFF;

BEGIN TRANSACTION;

insert into regions values(2,null,1,'New South Wales','New South Wales',null,null,1,0,'State');
insert into regions values(3,null,2,'Victoria','Victoria',null,null,1,0,'State');
insert into regions values(4,null,3,'Queensland','Queensland',null,null,1,0,'State');
insert into regions values(5,null,4,'South Australia','South Australia',null,null,1,0,'State');
insert into regions values(6,null,5,'Western Australia','Western Australia',null,null,1,0,'State');
insert into regions values(7,null,6,'Tasmania','Tasmania',null,null,1,0,'State');
insert into regions values(8,null,7,'Northern Territory','Northern Territory',null,null,1,0,'State');
insert into regions values(9,null,8,'Australian Capital Territory','Australian Capital Territory',null,null,1,0,'State');
-- insert into regions values(10,null,9,'Other Territories','Other Territories',null,null,1,0,'State');

insert into regions values(12,null,0,'ACT','ACT',null,null,1,0,'NRM');
insert into regions values(13,null,1,'Adelaide and Mount Lofty Ranges','Adelaide and Mount Lofty Ranges',null,null,1,0,'NRM');
insert into regions values(14,null,2,'Alinytjara Wilurara','Alinytjara Wilurara',null,null,1,0,'NRM');
-- insert into regions values(15,null,3,'Ashmore and Cartier Islands','Ashmore and Cartier Islands',null,null,1,0,'NRM');
insert into regions values(16,null,4,'Avon','Avon',null,null,1,0,'NRM');
insert into regions values(17,null,5,'Border Rivers Maranoa-Balonne','Border Rivers Maranoa-Balonne',null,null,1,0,'NRM');
insert into regions values(18,null,6,'Border Rivers-Gwydir','Border Rivers-Gwydir',null,null,1,0,'NRM');
insert into regions values(19,null,7,'Burdekin','Burdekin',null,null,1,0,'NRM');
insert into regions values(20,null,8,'Burnett Mary','Burnett Mary',null,null,1,0,'NRM');
insert into regions values(21,null,9,'Cape York','Cape York',null,null,1,0,'NRM');
insert into regions values(22,null,10,'Central West','Central West',null,null,1,0,'NRM');
-- insert into regions values(23,null,11,'Christmas Island','Christmas Island',null,null,1,0,'NRM');
-- insert into regions values(24,null,12,'Cocos Keeling Islands','Cocos Keeling Islands',null,null,1,0,'NRM');
insert into regions values(25,null,13,'Condamine','Condamine',null,null,1,0,'NRM');
insert into regions values(26,null,14,'Cooperative Management Area','Cooperative Management Area',null,null,1,0,'NRM');
insert into regions values(27,null,15,'Corangamite','Corangamite',null,null,1,0,'NRM');
insert into regions values(28,null,16,'Desert Channels','Desert Channels',null,null,1,0,'NRM');
insert into regions values(29,null,17,'East Gippsland','East Gippsland',null,null,1,0,'NRM');
insert into regions values(30,null,18,'Eyre Peninsula','Eyre Peninsula',null,null,1,0,'NRM');
insert into regions values(31,null,19,'Fitzroy','Fitzroy',null,null,1,0,'NRM');
insert into regions values(32,null,20,'Glenelg Hopkins','Glenelg Hopkins',null,null,1,0,'NRM');
insert into regions values(33,null,21,'Goulburn Broken','Goulburn Broken',null,null,1,0,'NRM');
insert into regions values(34,null,22,'Hawkesbury-Nepean','Hawkesbury-Nepean',null,null,1,0,'NRM');
-- insert into regions values(35,null,23,'Heard and McDonald Islands','Heard and McDonald Islands',null,null,1,0,'NRM');
insert into regions values(36,null,24,'Hunter-Central Rivers','Hunter-Central Rivers',null,null,1,0,'NRM');
insert into regions values(37,null,25,'Kangaroo Island','Kangaroo Island',null,null,1,0,'NRM');
insert into regions values(38,null,26,'Lachlan','Lachlan',null,null,1,0,'NRM');
insert into regions values(39,null,27,'Lower Murray Darling','Lower Murray Darling',null,null,1,0,'NRM');
insert into regions values(40,null,28,'Mackay Whitsunday','Mackay Whitsunday',null,null,1,0,'NRM');
insert into regions values(41,null,29,'Mallee','Mallee',null,null,1,0,'NRM');
insert into regions values(42,null,30,'Murray','Murray',null,null,1,0,'NRM');
insert into regions values(43,null,31,'Murrumbidgee','Murrumbidgee',null,null,1,0,'NRM');
insert into regions values(44,null,32,'Namoi','Namoi',null,null,1,0,'NRM');
-- insert into regions values(45,null,33,'Norfolk Island','Norfolk Island',null,null,1,0,'NRM');
insert into regions values(46,null,34,'North','North',null,null,1,0,'NRM');
insert into regions values(47,null,35,'North Central','North Central',null,null,1,0,'NRM');
insert into regions values(48,null,36,'North East','North East',null,null,1,0,'NRM');
insert into regions values(49,null,37,'North West','North West',null,null,1,0,'NRM');
insert into regions values(50,null,38,'Northern Agricultural','Northern Agricultural',null,null,1,0,'NRM');
insert into regions values(51,null,39,'Northern Gulf','Northern Gulf',null,null,1,0,'NRM');
insert into regions values(52,null,40,'Northern Rivers','Northern Rivers',null,null,1,0,'NRM');
-- insert into regions values(53,null,41,'Northern Rivers - Lord Howe Island','Northern Rivers - Lord Howe Island',null,null,1,0,'NRM');
insert into regions values(54,null,42,'Northern Territory','Northern Territory',null,null,1,0,'NRM');
insert into regions values(55,null,43,'Northern and Yorke','Northern and Yorke',null,null,1,0,'NRM');
insert into regions values(56,null,44,'Perth','Perth',null,null,1,0,'NRM');
insert into regions values(57,null,45,'Port Phillip and Western Port','Port Phillip and Western Port',null,null,1,0,'NRM');
insert into regions values(58,null,46,'Rangelands','Rangelands',null,null,1,0,'NRM');
insert into regions values(59,null,47,'South','South',null,null,1,0,'NRM');
-- insert into regions values(60,null,48,'South - Macquarie Islands','South - Macquarie Islands',null,null,1,0,'NRM');
insert into regions values(61,null,49,'South Australian Arid Lands','South Australian Arid Lands',null,null,1,0,'NRM');
insert into regions values(62,null,50,'South Australian Murray Darling Basin','South Australian Murray Darling Basin',null,null,1,0,'NRM');
insert into regions values(63,null,51,'South Coast','South Coast',null,null,1,0,'NRM');
insert into regions values(64,null,52,'South East','South East',null,null,1,0,'NRM');
insert into regions values(65,null,53,'South East Queensland','South East Queensland',null,null,1,0,'NRM');
insert into regions values(66,null,54,'South West','South West',null,null,1,0,'NRM');
insert into regions values(67,null,55,'South West Queensland','South West Queensland',null,null,1,0,'NRM');
insert into regions values(68,null,56,'Southern Gulf','Southern Gulf',null,null,1,0,'NRM');
insert into regions values(69,null,57,'Southern Rivers','Southern Rivers',null,null,1,0,'NRM');
insert into regions values(70,null,58,'Sydney Metro','Sydney Metro',null,null,1,0,'NRM');
insert into regions values(71,null,59,'Torres Strait','Torres Strait',null,null,1,0,'NRM');
insert into regions values(72,null,60,'West Gippsland','West Gippsland',null,null,1,0,'NRM');
insert into regions values(73,null,61,'Western','Western',null,null,1,0,'NRM');
insert into regions values(74,null,62,'Wet Tropics','Wet Tropics',null,null,1,0,'NRM');
insert into regions values(75,null,63,'Wimmera','Wimmera',null,null,1,0,'NRM');

insert into regions values(77,null,1,'Arnhem Coast','Arnhem Coast',null,null,1,0,'IBRA');
insert into regions values(78,null,2,'Arnhem Plateau','Arnhem Plateau',null,null,1,0,'IBRA');
insert into regions values(79,null,3,'Australian Alps','Australian Alps',null,null,1,0,'IBRA');
insert into regions values(80,null,4,'Avon Wheatbelt','Avon Wheatbelt',null,null,1,0,'IBRA');
insert into regions values(81,null,5,'Brigalow Belt North','Brigalow Belt North',null,null,1,0,'IBRA');
insert into regions values(82,null,6,'Brigalow Belt South','Brigalow Belt South',null,null,1,0,'IBRA');
insert into regions values(83,null,7,'Ben Lomond','Ben Lomond',null,null,1,0,'IBRA');
insert into regions values(84,null,8,'Broken Hill Complex','Broken Hill Complex',null,null,1,0,'IBRA');
insert into regions values(85,null,9,'Burt Plain','Burt Plain',null,null,1,0,'IBRA');
insert into regions values(86,null,10,'Carnarvon','Carnarvon',null,null,1,0,'IBRA');
insert into regions values(87,null,11,'Central Arnhem','Central Arnhem',null,null,1,0,'IBRA');
insert into regions values(88,null,12,'Central Kimberley','Central Kimberley',null,null,1,0,'IBRA');
insert into regions values(89,null,13,'Central Ranges','Central Ranges',null,null,1,0,'IBRA');
insert into regions values(90,null,14,'Channel Country','Channel Country',null,null,1,0,'IBRA');
insert into regions values(91,null,15,'Central Mackay Coast','Central Mackay Coast',null,null,1,0,'IBRA');
insert into regions values(92,null,16,'Coolgardie','Coolgardie',null,null,1,0,'IBRA');
insert into regions values(93,null,17,'Cobar Peneplain','Cobar Peneplain',null,null,1,0,'IBRA');
-- insert into regions values(94,null,18,'Coral Sea','Coral Sea',null,null,1,0,'IBRA');
insert into regions values(95,null,19,'Cape York Peninsula','Cape York Peninsula',null,null,1,0,'IBRA');
insert into regions values(96,null,20,'Daly Basin','Daly Basin',null,null,1,0,'IBRA');
insert into regions values(97,null,21,'Darwin Coastal','Darwin Coastal',null,null,1,0,'IBRA');
insert into regions values(98,null,22,'Dampierland','Dampierland',null,null,1,0,'IBRA');
insert into regions values(99,null,23,'Desert Uplands','Desert Uplands',null,null,1,0,'IBRA');
insert into regions values(100,null,24,'Davenport Murchison Ranges','Davenport Murchison Ranges',null,null,1,0,'IBRA');
insert into regions values(101,null,25,'Darling Riverine Plains','Darling Riverine Plains',null,null,1,0,'IBRA');
insert into regions values(102,null,26,'Einasleigh Uplands','Einasleigh Uplands',null,null,1,0,'IBRA');
insert into regions values(103,null,27,'Esperance Plains','Esperance Plains',null,null,1,0,'IBRA');
insert into regions values(104,null,28,'Eyre Yorke Block','Eyre Yorke Block',null,null,1,0,'IBRA');
insert into regions values(105,null,29,'Finke','Finke',null,null,1,0,'IBRA');
insert into regions values(106,null,30,'Flinders Lofty Block','Flinders Lofty Block',null,null,1,0,'IBRA');
insert into regions values(107,null,31,'Furneaux','Furneaux',null,null,1,0,'IBRA');
insert into regions values(108,null,32,'Gascoyne','Gascoyne',null,null,1,0,'IBRA');
insert into regions values(109,null,33,'Gawler','Gawler',null,null,1,0,'IBRA');
insert into regions values(110,null,34,'Geraldton Sandplains','Geraldton Sandplains',null,null,1,0,'IBRA');
insert into regions values(111,null,35,'Gulf Fall and Uplands','Gulf Fall and Uplands',null,null,1,0,'IBRA');
insert into regions values(112,null,36,'Gibson Desert','Gibson Desert',null,null,1,0,'IBRA');
insert into regions values(113,null,37,'Great Sandy Desert','Great Sandy Desert',null,null,1,0,'IBRA');
insert into regions values(114,null,38,'Gulf Coastal','Gulf Coastal',null,null,1,0,'IBRA');
insert into regions values(115,null,39,'Gulf Plains','Gulf Plains',null,null,1,0,'IBRA');
insert into regions values(116,null,40,'Great Victoria Desert','Great Victoria Desert',null,null,1,0,'IBRA');
insert into regions values(117,null,41,'Hampton','Hampton',null,null,1,0,'IBRA');
-- insert into regions values(118,null,42,'Indian Tropical Islands','Indian Tropical Islands',null,null,1,0,'IBRA');
insert into regions values(119,null,43,'Jarrah Forest','Jarrah Forest',null,null,1,0,'IBRA');
insert into regions values(120,null,44,'Kanmantoo','Kanmantoo',null,null,1,0,'IBRA');
insert into regions values(121,null,45,'King','King',null,null,1,0,'IBRA');
insert into regions values(122,null,46,'Little Sandy Desert','Little Sandy Desert',null,null,1,0,'IBRA');
insert into regions values(123,null,47,'MacDonnell Ranges','MacDonnell Ranges',null,null,1,0,'IBRA');
insert into regions values(124,null,48,'Mallee','Mallee',null,null,1,0,'IBRA');
insert into regions values(125,null,49,'Murray Darling Depression','Murray Darling Depression',null,null,1,0,'IBRA');
insert into regions values(126,null,50,'Mitchell Grass Downs','Mitchell Grass Downs',null,null,1,0,'IBRA');
insert into regions values(127,null,51,'Mount Isa Inlier','Mount Isa Inlier',null,null,1,0,'IBRA');
insert into regions values(128,null,52,'Mulga Lands','Mulga Lands',null,null,1,0,'IBRA');
insert into regions values(129,null,53,'Murchison','Murchison',null,null,1,0,'IBRA');
insert into regions values(130,null,54,'Nandewar','Nandewar',null,null,1,0,'IBRA');
insert into regions values(131,null,55,'Naracoorte Coastal Plain','Naracoorte Coastal Plain',null,null,1,0,'IBRA');
insert into regions values(132,null,56,'New England Tablelands','New England Tablelands',null,null,1,0,'IBRA');
insert into regions values(133,null,57,'NSW North Coast','NSW North Coast',null,null,1,0,'IBRA');
insert into regions values(134,null,58,'Northern Kimberley','Northern Kimberley',null,null,1,0,'IBRA');
insert into regions values(135,null,59,'NSW South Western Slopes','NSW South Western Slopes',null,null,1,0,'IBRA');
insert into regions values(136,null,60,'Nullarbor','Nullarbor',null,null,1,0,'IBRA');
insert into regions values(137,null,61,'Ord Victoria Plain','Ord Victoria Plain',null,null,1,0,'IBRA');
insert into regions values(138,null,62,'Pine Creek','Pine Creek',null,null,1,0,'IBRA');
insert into regions values(139,null,63,'Pilbara','Pilbara',null,null,1,0,'IBRA');
-- insert into regions values(140,null,64,'Pacific Subtropical Islands','Pacific Subtropical Islands',null,null,1,0,'IBRA');
insert into regions values(141,null,65,'Riverina','Riverina',null,null,1,0,'IBRA');
-- insert into regions values(142,null,66,'Subantarctic Islands','Subantarctic Islands',null,null,1,0,'IBRA');
insert into regions values(143,null,67,'South East Coastal Plain','South East Coastal Plain',null,null,1,0,'IBRA');
insert into regions values(144,null,68,'South East Corner','South East Corner',null,null,1,0,'IBRA');
insert into regions values(145,null,69,'South Eastern Highlands','South Eastern Highlands',null,null,1,0,'IBRA');
insert into regions values(146,null,70,'South Eastern Queensland','South Eastern Queensland',null,null,1,0,'IBRA');
insert into regions values(147,null,71,'Simpson Strzelecki Dunefields','Simpson Strzelecki Dunefields',null,null,1,0,'IBRA');
insert into regions values(148,null,72,'Stony Plains','Stony Plains',null,null,1,0,'IBRA');
insert into regions values(149,null,73,'Sturt Plateau','Sturt Plateau',null,null,1,0,'IBRA');
insert into regions values(150,null,74,'Southern Volcanic Plain','Southern Volcanic Plain',null,null,1,0,'IBRA');
insert into regions values(151,null,75,'Swan Coastal Plain','Swan Coastal Plain',null,null,1,0,'IBRA');
insert into regions values(152,null,76,'Sydney Basin','Sydney Basin',null,null,1,0,'IBRA');
insert into regions values(153,null,77,'Tanami','Tanami',null,null,1,0,'IBRA');
insert into regions values(154,null,78,'Tasmanian Central Highlands','Tasmanian Central Highlands',null,null,1,0,'IBRA');
-- insert into regions values(155,null,79,'Tiwi Cobourg','Tiwi Cobourg',null,null,1,0,'IBRA');
insert into regions values(156,null,80,'Tasmanian Northern Midlands','Tasmanian Northern Midlands',null,null,1,0,'IBRA');
insert into regions values(157,null,81,'Tasmanian Northern Slopes','Tasmanian Northern Slopes',null,null,1,0,'IBRA');
insert into regions values(158,null,82,'Tasmanian South East','Tasmanian South East',null,null,1,0,'IBRA');
insert into regions values(159,null,83,'Tasmanian Southern Ranges','Tasmanian Southern Ranges',null,null,1,0,'IBRA');
insert into regions values(160,null,84,'Tasmanian West','Tasmanian West',null,null,1,0,'IBRA');
insert into regions values(161,null,85,'Victoria Bonaparte','Victoria Bonaparte',null,null,1,0,'IBRA');
insert into regions values(162,null,86,'Victorian Midlands','Victorian Midlands',null,null,1,0,'IBRA');
insert into regions values(163,null,87,'Warren','Warren',null,null,1,0,'IBRA');
insert into regions values(164,null,88,'Wet Tropics','Wet Tropics',null,null,1,0,'IBRA');
insert into regions values(165,null,89,'Yalgoo','Yalgoo',null,null,1,0,'IBRA');

-- insert into regions values(166,null,1,'Kimberley','Kimberley',null,null,1,0,'subWA');
-- insert into regions values(167,null,1,'Top End','Top End',null,null,1,0,'subNT');
-- insert into regions values(168,null,2,'Table Lands','Table Lands',null,null,1,0,'subNT');
-- insert into regions values(169,null,3,'Arid Lands','Arid Lands',null,null,1,0,'subNT');
-- insert into regions values(170,null,4,'Gulf Savanna','Gulf Savanna',null,null,1,0,'subNT');

COMMIT;
